language: c
services:
  - docker

# We cache the node_modules and other Yarn related files to speed up the build
cache: yarn

before_install:
  - docker pull fezvr4sta/node:11.1.0-alpine-yarn-flow
  - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -v $HOME/.yarn-cache:/root/.yarn-cache -it -d --name build fezvr4sta/node:11.1.0-alpine-yarn-flow bash

install:
  - docker exec build sh -c 'cd /root/src/; yarn --frozen-lockfile'

jobs:
  include:
    - stage: type checks and unit tests
      script:
        - docker exec build sh -c 'cd /root/src/; ./node_modules/.bin/flow check'
        - docker exec build sh -c 'cd /root/src/; ./node_modules/.bin/react-app-rewired test --coverage --colors'
    - stage: publish gh-pages
      script: docker exec build sh -c 'cd /root/src/; yarn build'
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: styleguide
        on:
          branch: master
    - stage: publish to Artifactory
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: skip
      deploy:
        skip_cleanup: true # Keep all the artifacts generated on prev steps
        provider: script
        script: bash scripts/deploy.sh
