name: ci

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  workflow_dispatch:
    debug_console:
      type: choice
      description: 'turn on tmate SSH connection for debugging. (on/off/force)'
      default: 'off'
      options:
      - "on"
      - "off"
      - "force"

jobs:
  cancel:
    runs-on: public-runner
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
      with:
        all_but_latest: true

  test-and-deploy:
    runs-on: public-runner
    steps:
    - name: Checkout Master
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        fetch-depth: 50
        token: ${{ secrets.QUID_BOT_TOKEN }}

    - name: Checkout Non-Master
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      if: ${{ github.ref != 'refs/heads/master' }}

    - name: Install Yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
        echo "$HOME/.yarn/bin" >> $GITHUB_PATH

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: 11.10.1

    - name: Install Dependencies
      run: |
        yarn --frozen-lockfile
        npm install -g flow-bin@0.100.0
        npm install -g react-app-rewired@^2.1.1
        npm install -g react-scripts@^3.0.1

    - name: Type Checks and Unit Tests
      run: |
        flow check
        react-app-rewired test --coverage --colors

    - name: Build
      if: ${{ github.ref == 'refs/heads/master' }}
      run: yarn build

    - name: Publish gh-pages
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./styleguide
        keep_files: true
        user_name: 'quid-bot'
        user_email: 'infratructure@quid.com'
        cname: ui.quid.com

    - name: Publish to npm
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        export GITHUB_NAME=quid-bot
        export GITHUB_EMAIL=infratructure@quid.com
        export QUID_BOT_TOKEN=${{ secrets.QUID_BOT_TOKEN }}
        export AUTOMATED_WRITE_AUTH=${{ secrets.AUTOMATED_WRITE_AUTH }}
        bash scripts/deploy.sh

    - name: Setup tmate session
      if: ${{ (failure() && inputs.debug_console == 'on') || inputs.debug_console == 'force' }}
      uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3
